# General parameters
dataset: H_sh_300_options
model_name: SAINT_3D # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
# MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT,SAINT_v2.SAINT_3d
objective: binary  # Don't change binary_f1 binary
# 如果是 binary或者regression 那么num_classes为1

pretrain: True
pretrain_epochs: 17

use_pretrain_data: False

# optimize_hyperparameters: True
use_gpu: True
# use one GPU parameters
gpu_index: 5
# use GPU data_parallel parameters
gpu_ids: [ 0, 1 ]


data_parallel: False

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: maximize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: False
target_encode: False
one_hot_encode: False

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 10
epochs: 500
logging_period: 20



# About the data
num_classes: 1  # for classification
num_features: 195
cat_idx: [ 0, 28, 38, 39, 67, 77, 78,106, 116,117,145,155,156,184,194]
# cat_dims: will be automatically set.
#cat_dims: [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ]