echo '======================================'>>pid/transformer-code-comments.pid
python transformer-code-comments.py 3 0 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 6 0 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 9 0 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 16 0 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 3 1 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 6 1 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 9 1 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 16 1 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 3 2 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 6 2 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 9 2 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 16 2 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 3 3 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 6 3 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 9 3 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 16 3 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 3 4 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 6 4 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 9 4 & echo $! >> pid/transformer-code-comments.pid
python transformer-code-comments.py 16 4 & echo $! >> pid/transformer-code-comments.pid